#this code will allow you to search for (Major) Japanese cities' sister cities
print("Enter a major Japanese city to get the corresponding sister city/cities.")
def main():
   word_dictionary = {
       'Tokyo' : 'Beijing (China), Berlin (Germany), Cairo (Egypt), Jakarta (Indonesia), London (United Kingdom), Moscow (Russia), New South Wales (Australia), New York City (United States), Paulo State (Brazil)',
       'Yokohama': 'Romania Constanţa Romania), Lyon (France), Manila (Philippines), Mumbai (India), Odessa (Ukraine), San Diego (United States), Shanghai (China), Vancouver (Canada)',
       'Osaka': 'Chicago (United States), Hamburg (Germany), Melbourne (Australia), Milan (Italy), Saint Petersburg (Russia), São Paulo (Brazil)',
       'Nagoya': 'Los Angeles (United States), Mexico City (Mexico), Reims (France), Sydney (Australia), Turin (Italy)',
       'Sapporo': 'Daejeon (South Korea), Munich (Germany), Novosibirsk (Russia), Portland (United States)',
       'Fukuoka': 'Atlanta (United States), Auckland (New Zealand), Bordeaux (France), Busan (South Korea), Guangzhou (China), Ipoh (Malaysia)',
       'Kobe': ' Barcelona Spain), Brisbane (Australia), Incheon (South Korea), Marseille (France), Riga (Latvia), Rio de Janeiro (Brazil), Seattle (United States), Tianjin (China)',
       'Kawasaki': 'Baltimore (United States), Rijeka (Croatia), Shenyang (China), Wollongong (Australia)',
       'Kyoto': 'Boston (United States, Cologne (Germany, Florence (Italy), Guadalajara (Mexico), Kyiv (Ukraine), Prague (Czech Republic), Xian (China), Zagreb (Croatia)',
       'Saitama': 'Hamilton (New Zealand), Nanaimo (Canada), Pittsburgh (United States), Richmond (United States), Toluca (Mexico), Zhengzhou (China)',
       'Hiroshima': 'Chongqing (China), Daegu (South Korea), Hanover (Germany), Honolulu (United States), Montreal (Canada), Volgograd (Russia)',
       'Chiba': 'Paraguay Asunción (Paraguay), Houston (United States), Tianjin (China), Wujiang (Suzhou)(China), Quezon City (Philippines), North Vancouver (Canada)',
       'Kitakyushu': 'Dalian (China), Haiphong (Vietnam), Incheon (South Korea), Norfolk (United States), Tacoma (United States), Phnom Penh (Cambodia)',
       'Sendai': 'Acapulco (Mexico), Changchun (China), Gwangju (South Korea), Dallas (United States), Riverside (United States), Minsk (Belarus),Rennes (France)',
       'Sakai': 'Berkeley (United States), Lianyungang (China), Wellington (New Zealand)',
       'Niigata': 'Galveston (United States), Harbin (China), Kingston upon Hull (United Kingdom), Nantes (France), Vladivostok (Russia), Birobidzhan (Russia),Khabarovsk (Russia)',
       'Hamamatsu': 'Camas (United States), Chehalis (United States), Hangzhou (China), Porterville (United States), Rochester Rochester',
       'Kumamoto': 'Fukui (Japan), Guilin (China), Heidelberg, (Germany), San Antonio (United States)',
       'Sagamihara':'Wuxi (China)',
       'Okayama': 'Hsinchu (Taiwan), Luoyang (China), Plovdiv (Bulgaria), San José (Costa Rica), Guam Guam (United States), San Jose (United States)',
       'Naha': 'Fuzhou (China), Honolulu (United States), Nichinan (Japan), São Vicente (Brazil)',
       'Aomori': 'Kecskemét (Hungary), Pyeongtaek (South Korea)',
       'Fukui': 'Fullerton, (United States), New Brunswick (United States), Hangzhou, (China), Kumamoto, (Japan)',
       'Kagoshima': 'Puli (Taiwan), Suncheon (South Korea)',
       'Nagano': 'Clearwater (United States), Shijiazhuang (China)',
       'Nagasaki': 'Fuzhou (China), Leiden (Netherlands), Porto (Portugal), Saint Paul (United States), Santos (Brazil), Vaux-sur-Aure (France)',
       'Nara': 'Canberra (Australia), Gyeongju (South Korea), Kōriyama (Japan), Obama (Japan), Toledo (Spain), Versailles (France), Xian (China), Yangzhou (China)',
       'Nishinomiya': 'Shaoxing (China), Spokane (United States)',
       'Tottori': 'Cheongju (South Korea, Hanau Germany, Himeji (Japan), Iwakuni (Japan), Kōriyama (Japan), Kushiro (Japan)',
       'Toyama': 'Dubbo (Australia), Durham (United States), Mogi das Cruzes (Brazil)',
       'Toyota': 'Derbyshire (United Kingdom), South Derbyshire (United Kingdom), Detroit (United States)',
       'Utsunomiya': 'Auckland (New Zealand), Orléans (France), Qiqihar (China, Tulsa (United States)',
       'Wakayama': 'Bakersfield (United States), Jeju City (South Korea), Jinan (China), Richmond (Canada)',
       'Yamagata': 'Boulder (United States), Jilin City (China), Kitzbühel (Austria), Swan Hill (Australia)',
       'Yokosuka': 'Brest (France),Corpus Christi (United States), Fremantle (Australia), Medway (United Kingdom)',
       'Kanazawa': 'Buffalo (United States), Ghent (Belgium), Irkutsk (Russia), Jeonju (South Korea), Nancy (France), Porto Alegre (Brazil)',
       'Hakodate': 'Goyang (South Korea), Halifax (Canada), Lake Macquarie (Australia), Vladivostok (Russia)',
       'Fuji': 'Jiaxing (China), Oceanside (United States)',
       'Chigasaki': 'Honolulu (United States)',
       'Odawara': 'Chula Vista (United States), Hachiōji (Japan), Nikkō (Japan), Yorii (Japan)',
       'Matsudo': 'Whitehorse (Australia)',
       'Tokushima': 'Leiria (Portugal), Saginaw (United States)',
       'Tsukuba': 'Bochum (Germany), Cambridge (United States), Grenoble (France), Irvine (United States), Milpitas (United States), Shenzhen (China)',
       'Akita': 'Hitachiōta (Japan), Kenai (United States), Lanzhou (China), Passau (Germany), St. Cloud (United States), Vladivostok, (Russia)',
       'Atami': 'Beppu (Japan), Cascais (Portugal), Sanremo (Italy), Zhuhai (China)',
       'Beppu': 'Bath England (United Kingdom), Mokpo 9South Korea), Rotorua Lakes (New Zealand), Yantai (China)',
       'Hakone': 'Jasper (Canada), Taupo (New Zealand)',
       'Himeiji': 'Adelaide (Australia), Changwon (South Korea), Charleroi (Belgium), Curitiba (Brazil), Matsumoto (Japan), Phoenix (United States), Taiyuan (China), Tottori (Japan)',
       'Hitachi': 'Birmingham (United States), Kiryū (Japan), Tauranga (New Zealand)',
       'Imabari': 'Lakeland United States), Onomichi (Japan), Ōta (Japan), Panama City (Panama)',
       'Inuyama': 'Davis (United States), Haman (South Korea), Nichinan (Japan), Sankt Goarshausen (Germany), Tateyama (Japan), Xiangyang (China)',
       'Itami': 'Foshan (China), Hasselt (Belgium), Ōmura (Japan)',
       'Narita': 'Foxton (Horowhenua) (New Zealand), San Bruno (United States), Taoyuan (Taiwan), Xianyang (China)',
       'Naruto': 'Kiryū (Japan), Lüneburg (Germany)',
       'Nikko': 'Hachiōji (Japan), Odawara (Japan), Rapid City (United States), Tomakomai (Japan)',
       'Obama': ' Gyeongju (South Korea, Kawagoe (Japan), Nara (Japan)',
       'Okinawa': 'Lakewood (United States), Tōkai (Japan), Toyonaka (Japan), Yonezawa (Japan)',
       'Saga': 'Cussac-Fort-Médoc (France), Glens Falls (United States), Warren County (United States)Lianyungang (China)',
       'Sasebo': 'Albuquerque (United States), Coffs Harbour (Australia), Kokonoe (Japan), Paju (South Korea)',
       'Shimonoseki': 'Busan (South Korea), Istanbul (Turkey), Pittsburg (United States), Qingdao (China)',
       'Shizuoka': 'Cannes (France), Jōetsu (Japan), Muroran (Japan), Omaha (United States), Shelbyville (United States), Stockton (United States)',
       'Ueda': 'Broomfield (United States), Davos (Switzerland), Jōetsu (Japan), Kamakura (Japan), Kudoyama (Japan), Toyooka (Japan)',
       'Joetsu': 'Shizuoka (Japan), Ena (Japan), Hokuto (Japan), Itakura (Japan), Iwanai (Japan), Muroran (Japan), Pohang (South Korea), Hunchun (China), Lilienfeld (Austria),',
       'Iwakuni': 'Everett (United States),  Jundiaí (Brazil), Tottori (Japan)',
   }

   while True:
       word = input("Enter a Japanese city:")
       if word == "":
           break
       if word in word_dictionary:
           print(word, ":", word_dictionary[word])
main()